<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pilihan Fakultas_object-cover rounded-lg</name>
   <tag></tag>
   <elementGuidId>e3cfea27-3364-4c63-9a79-ef421f2a86b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div[2]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.object-cover.rounded-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5307d338-201c-410c-9a49-a7d19dad6a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Picture of the author</value>
      <webElementGuid>29a1aa40-a128-423b-8a74-40ddb55ae89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>495dd466-2992-4a3b-a728-09a3cb773bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>408</value>
      <webElementGuid>68ee80c1-3588-404a-af87-d77ebe50d8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>224</value>
      <webElementGuid>d34bd34f-262f-4d08-af17-feb3104302f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>401fea40-6f93-48c6-93c6-943f93b2e037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8de22797-bb63-4cf9-b712-b9fac552a0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-cover rounded-lg</value>
      <webElementGuid>f151c22d-9bb7-4e2e-9459-f7da3738530d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/choicefaculty2.ed9d815d.svg</value>
      <webElementGuid>a2f3b480-71d3-4a45-8a39-dc782c0120e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;px-8&quot;]/div[@class=&quot;grid grid-cols-1 gap-4 pb-40 lg:grid-cols-3&quot;]/a[1]/div[@class=&quot;px-3 rounded-lg  flex auto p-4 flex-col&quot;]/img[@class=&quot;object-cover rounded-lg&quot;]</value>
      <webElementGuid>6c6aacc9-a43d-4875-a54d-636f4a841705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/div/a/div/img</value>
      <webElementGuid>7a7718d0-0745-43b2-b8e2-40cb6c9897c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Picture of the author']</value>
      <webElementGuid>3dca8dad-6362-48b5-aaed-2348de0a34a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>e000d6d9-f084-45b7-a0fb-733c7d0e8a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Picture of the author' and @src = '/_next/static/media/choicefaculty2.ed9d815d.svg']</value>
      <webElementGuid>cc63aad2-e74c-46d3-b9b1-d4e42e62a500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
