<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password</name>
   <tag></tag>
   <elementGuidId>19e11895-4cda-4e39-8552-d7b3ee3fde47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c5c6e74-7fd3-42d1-9878-5aa77278ed3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1240b98d-7567-4323-b1db-021e4e78c8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>control</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>ecdcfe11-332e-4488-a89d-6e6b69e62c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ecc82a0f-0f64-40c2-8845-5bced8dddd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>************</value>
      <webElementGuid>c19540b1-3fe1-4e37-8743-a5e6365e466b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>7b505765-7e4e-4a36-a538-275b1a3685fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none focus:outline-none w-full text-[#000] text-sm border-[0.5px] border-neutral-400 shadow-sm py-4 rounded-lg  px-4 </value>
      <webElementGuid>5c3d3a90-4369-495a-9579-09bd477e1298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;w-full bg-neutral-100 flex justify-center items-center lg:py-10 lg:px-14 md:p-8 sm:p-6 p-4 h-screen&quot;]/section[@class=&quot;flex items-center bg-white w-full h-full rounded-lg shadow-lg&quot;]/div[@class=&quot;flex-col md:gap-y-[57px] gap-y-6 items-center justify-center p-6 flex h-full w-full lg:w-1/2&quot;]/div[@class=&quot;flex flex-col w-full items-start pb-[37px] justify-start&quot;]/form[@class=&quot;flex flex-col w-full justify-start&quot;]/section[@class=&quot;flex flex-col w-auto my-1 gap-y-2&quot;]/section[@class=&quot;relative flex items-center w-auto&quot;]/input[@class=&quot;outline-none focus:outline-none w-full text-[#000] text-sm border-[0.5px] border-neutral-400 shadow-sm py-4 rounded-lg  px-4&quot;]</value>
      <webElementGuid>d86abac2-b1ad-4cb3-a40c-4bbd640ce665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>36d4c2ad-6dd0-41e7-ade3-f89f406e3cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section/div[2]/div[2]/form/section[2]/section/input</value>
      <webElementGuid>17a890e5-e986-4383-943b-449764088024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section/input</value>
      <webElementGuid>49d495e3-2bb9-4b74-ad58-7b49bc0c29cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = '************']</value>
      <webElementGuid>bb115335-f00d-44a9-9e14-3395474b9577</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
