<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Koin_sso__icon__login_top</name>
   <tag></tag>
   <elementGuidId>9357bde9-1cb3-4691-8fd2-133193971ec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='sso__icon__login_top']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sso__icon__login_top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>808c3ed5-3fec-4b94-afb5-e0fc11032e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sso__icon__login</value>
      <webElementGuid>32d9eb94-fa50-411f-8516-e6d8fae73241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sso__icon__login_top</value>
      <webElementGuid>f7293fb1-d18d-40f9-89ea-fea14e4e5e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sso__icon__login_top&quot;)</value>
      <webElementGuid>d9825232-f080-4243-a2ff-f4dbc2eda341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='sso__icon__login_top']</value>
      <webElementGuid>8ddd3bc5-682d-42e1-805a-b1a792a2d6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>7b0c7e89-f658-4abe-a61c-607d31a3966a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'sso__icon__login_top']</value>
      <webElementGuid>98f163c7-e048-4cf4-9bf5-c5c7398e0d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
