<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Belum</name>
   <tag></tag>
   <elementGuidId>a9926234-e2b6-4c2f-8ba1-fae13bd1f346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>340bd006-0aaf-409a-bd4e-0394e827f2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[230px] h-[56px] bg-[#106FA4] rounded-[8px] text-white</value>
      <webElementGuid>b4682e58-56b9-4a4c-a49a-55df592f367b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e26d5af0-780b-459e-b1bd-0c1d8bc5507b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum</value>
      <webElementGuid>f3408a7c-252d-4c5e-868b-01224fef671c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;min-h-screen bg-[#FAFAFA] px-[70px] w-full&quot;]/div[2]/div[2]/div[@class=&quot;p-8 overflow-auto whitespace-nowrap&quot;]/div[@class=&quot;relative z-50&quot;]/div[@class=&quot;fixed inset-0 z-10 overflow-y-auto&quot;]/div[@class=&quot;flex items-center justify-center w-full min-h-full p-4 text-center sm:items-center sm:p-0&quot;]/div[@class=&quot;relative w-auto overflow-hidden text-left transition-all transform rounded-lg shadow-xl sm:my-8 undefined&quot;]/div[@class=&quot;w-full px-4 pt-5 pb-4 bg-white sm:p-6 sm:pb-4&quot;]/div[@class=&quot;mt-3 text-center sm:mt-0 sm:text-left&quot;]/div[@class=&quot;flex items-center w-full&quot;]/div[@class=&quot;flex flex-col items-center justify-center w-full py-10 text-center dark:bg-[#222529] !h-80 !w-[100%] text-md py-10&quot;]/div[@class=&quot;flex w-full flex-col justify-center&quot;]/div[@class=&quot;flex gap-3 my-2 py-4&quot;]/button[@class=&quot;w-[230px] h-[56px] bg-[#106FA4] rounded-[8px] text-white&quot;]</value>
      <webElementGuid>08b6d520-9ff2-4d82-ad46-020150307c49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>ca82e32e-9bca-475f-afc1-bd39316086ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section/div[2]/div[2]/div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>b3bc3c4d-7af3-4171-962d-5d6f1be508bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pernah'])[1]/following::button[1]</value>
      <webElementGuid>e961d013-a543-43ab-85cf-c2970bfca481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda sudah mempelajari mata kuliah ini?'])[1]/following::button[2]</value>
      <webElementGuid>4bd0655f-bd2b-4153-98ea-8c6219bf7c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Belum']/parent::*</value>
      <webElementGuid>db358361-c03b-4b6d-88f2-aa629a513702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c383a24d-c159-43c5-9744-8e09f112d2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Belum' or . = 'Belum')]</value>
      <webElementGuid>373f1816-571b-45c2-8d68-51ebb8d2dc52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
