<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect</name>
   <tag></tag>
   <elementGuidId>ffcbcfbf-7ac5-4b6e-ba48-945a407dd7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg > rect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>be98b815-d575-4301-8dad-0ad1e3ca5057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0.311523</value>
      <webElementGuid>b33534e6-60aa-420d-8710-0d8de1ea84f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24.3762</value>
      <webElementGuid>3d5e6191-6584-4305-b647-8b29f5c52aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24.3762</value>
      <webElementGuid>846e2067-2c93-4ff6-8c23-833c7e666bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>12.1881</value>
      <webElementGuid>7a518672-6b76-4973-9bde-3f4cba23c4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#106FA4</value>
      <webElementGuid>a928b438-d16a-4574-908f-69f8d2cf96f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;min-h-screen bg-[#FAFAFA] px-[70px] w-full&quot;]/div[2]/div[2]/div[@class=&quot;p-8 overflow-auto whitespace-nowrap&quot;]/div[@class=&quot;grid grid-flow-row auto-rows-auto&quot;]/div[@class=&quot;grid grid-flow-col auto-cols-min mx-auto border border-[#e5e7eb] divide-neutral-400 dark:divide-gray-700 w-full text-[16px]&quot;]/div[@class=&quot;w-[177px] dark:divide-gray-700 lg:text-start text-center py-3 font-medium md:text-[16px] lg:text-[16px] text-[10px] dark:bg-transparent&quot;]/button[@class=&quot;flex gap-2 items-center p-4 font-semibold text-blue-600&quot;]/svg[1]/rect[1]</value>
      <webElementGuid>79453de5-a094-457b-ab8c-5e41a1765b74</webElementGuid>
   </webElementProperties>
</WebElementEntity>
