<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sertifikat</name>
   <tag></tag>
   <elementGuidId>f623b6e6-486a-48a0-abd5-a560656f0d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-tab-:rc:']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c64c4177-e5ff-4aa7-b364-ab542112bc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> py-2 px-4 cursor-pointer</value>
      <webElementGuid>a6822a1b-f181-4b71-861b-7f997340cc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sertifikat</value>
      <webElementGuid>b8b68f53-ff7c-42e3-b2c7-a7af4f03337e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-tab-:rc:&quot;)/div[@class=&quot;py-2 px-4 cursor-pointer&quot;]</value>
      <webElementGuid>fd70396f-1c45-47a7-a179-4afec9bce0e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-tab-:rc:']/div</value>
      <webElementGuid>84005065-3327-4238-9df1-e490b7986cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nilai'])[1]/following::div[2]</value>
      <webElementGuid>970c8986-fb29-44d9-9ed7-8092ceb08528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nilai &amp; Sertfikat'])[1]/following::div[5]</value>
      <webElementGuid>8ef570dd-b4dd-43bb-ad3a-1e41439f771a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semester'])[1]/preceding::div[2]</value>
      <webElementGuid>726f29b4-e09b-4d6f-8f97-91cd5477d928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKS Diambil'])[1]/preceding::div[2]</value>
      <webElementGuid>bc2f71a4-cd40-4f36-846b-4b278594fc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sertifikat']/parent::*</value>
      <webElementGuid>c5675e2c-350f-4fb1-91ae-6ad65ded75c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>be8d0906-4a00-4ae0-9b2a-efb857a78fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sertifikat' or . = 'Sertifikat')]</value>
      <webElementGuid>3a6893bc-5d9b-4412-9db4-66845e0da2ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
