<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Belum</name>
   <tag></tag>
   <elementGuidId>f34fefc7-9529-4698-949c-0cf51411adcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a256da60-067d-43c5-ba03-1d3a3b83a167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[230px] h-[56px] bg-[#106FA4] rounded-[8px] text-white</value>
      <webElementGuid>4b785631-8937-48e2-8695-e02924c3dae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da55d376-95a1-4216-9c74-27e392688dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum</value>
      <webElementGuid>b6141748-f164-43db-948d-ed2ed3bb3e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;min-h-screen bg-[#FAFAFA] px-[70px] w-full&quot;]/div[2]/div[2]/div[@class=&quot;p-8 overflow-auto whitespace-nowrap&quot;]/div[@class=&quot;relative z-50&quot;]/div[@class=&quot;fixed inset-0 z-10 overflow-y-auto&quot;]/div[@class=&quot;flex items-center justify-center w-full min-h-full p-4 text-center sm:items-center sm:p-0&quot;]/div[@class=&quot;relative w-auto overflow-hidden text-left transition-all transform rounded-lg shadow-xl sm:my-8 undefined&quot;]/div[@class=&quot;w-full px-4 pt-5 pb-4 bg-white sm:p-6 sm:pb-4&quot;]/div[@class=&quot;mt-3 text-center sm:mt-0 sm:text-left&quot;]/div[@class=&quot;flex items-center w-full&quot;]/div[@class=&quot;flex flex-col items-center justify-center w-full py-10 text-center dark:bg-[#222529] !h-80 !w-[100%] text-md py-10&quot;]/div[@class=&quot;flex w-full flex-col justify-center&quot;]/div[@class=&quot;flex gap-3 my-2 py-4&quot;]/button[@class=&quot;w-[230px] h-[56px] bg-[#106FA4] rounded-[8px] text-white&quot;]</value>
      <webElementGuid>4c914510-8672-4ceb-be77-7e770c590fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>22954873-0ddc-4d18-bc66-8c548f94fa2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section/div[2]/div[2]/div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>e775bdf2-a858-4af4-a81a-ab168f5c14a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pernah'])[1]/following::button[1]</value>
      <webElementGuid>ebc01a9a-6fe2-4c11-bfe1-ffdc5dff1e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda sudah mempelajari mata kuliah ini?'])[1]/following::button[2]</value>
      <webElementGuid>35093a25-5a0e-4b8f-9998-1f85a311e541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Belum']/parent::*</value>
      <webElementGuid>018dd8b0-bfdc-425a-86b3-bfb117fa9709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>020877ee-09bf-4d52-85f4-1a1373fda67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Belum' or . = 'Belum')]</value>
      <webElementGuid>916d2651-6cee-4d79-8697-af524b8a36a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
