<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ditugaskan</name>
   <tag></tag>
   <elementGuidId>ff3f8ae7-93cd-43f4-835d-897c9c691210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/section[2]/div/div/ul/li[2]/button/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ecf4a9c4-6494-4e4a-8dac-0e7d322eb3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block p-4      rounded-t-lg active hover:border-gray-300 dark:hover:text-gray-300  dark:text-[#0B568D] </value>
      <webElementGuid>c1372686-2635-4626-b218-02abbff6cb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>f5c917dc-d7e0-4b43-8ae6-aa4701095d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ditugaskan</value>
      <webElementGuid>a1eda395-7f5f-4abb-8482-f76da1ad55ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;lg:px-20 md:px-10 px-5 py-3 w-full mt-[36px] drop-shadow-md mb-3 min-h-screen&quot;]/div[@class=&quot;bg-white h-full rounded-[8px] dark:bg-gray-800&quot;]/div[@class=&quot;text-[20px] font-semibold text-center text-[#262626] border-b border-gray-200 hover:text-[#000] px-[50px] mb-10&quot;]/ul[@class=&quot;flex flex-wrap&quot;]/li[@class=&quot;mr-2&quot;]/button[1]/a[@class=&quot;inline-block p-4      rounded-t-lg active hover:border-gray-300 dark:hover:text-gray-300  dark:text-[#0B568D]&quot;]</value>
      <webElementGuid>43a70c4e-1b0d-4a2f-a95d-cfc4c9e02bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section[2]/div/div/ul/li[2]/button/a</value>
      <webElementGuid>9c14b466-970c-4bb7-a3dd-956911f094d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ditugaskan')]</value>
      <webElementGuid>52e3c549-22f3-4313-8575-2a28a771bc35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Tugas'])[1]/following::a[1]</value>
      <webElementGuid>685e86c0-412b-4386-b315-ef7cd6f98530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penugasan'])[4]/following::a[2]</value>
      <webElementGuid>f67e067e-cb15-4f75-83ad-7f0092d2e26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terlambat'])[1]/preceding::a[1]</value>
      <webElementGuid>ed47ba2d-2ff4-40ed-a4fc-737163ee06be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Dinilai'])[1]/preceding::a[2]</value>
      <webElementGuid>b2cc1c8d-472a-4bc7-b422-b9bf71327b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ditugaskan']/parent::*</value>
      <webElementGuid>616294ce-ad3c-4613-a92f-ce81997893bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button/a</value>
      <webElementGuid>67571365-ad48-4773-b294-e6239ddb99ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Ditugaskan' or . = 'Ditugaskan')]</value>
      <webElementGuid>090dd72d-22fb-4763-872d-0c87c27176f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
