<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pembiayaan dan Optimalisasi Bisnis_obje_c77565</name>
   <tag></tag>
   <elementGuidId>4d5d434f-079d-49c2-bd7a-6f87b1f85b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div[2]/div/a[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > div.px-3.rounded-lg.flex.auto.p-4.flex-col > img.object-cover.rounded-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>89cb88c1-3698-4b9a-bc4d-7b28939d4e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Picture of the author</value>
      <webElementGuid>93cde8ea-8ad6-441c-a693-589f5f9823fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9dcd0ac9-93f3-4388-a25b-fb57acd28b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>408</value>
      <webElementGuid>41e9a441-f652-4d84-b4a2-dce5713b95dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>224</value>
      <webElementGuid>6428a59e-af0f-45c0-84ee-96a036adb8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>9fb204b3-44aa-454a-bc78-25e87ee5628b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>48c7e8a0-fd6d-453e-a9fb-9504cf754042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-cover rounded-lg</value>
      <webElementGuid>8c85b820-af23-40f9-a65b-a2d9ad4a33a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/choicefaculty2.ed9d815d.svg</value>
      <webElementGuid>325002e0-48eb-4bfa-b3b5-95136e327490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;px-8&quot;]/div[@class=&quot;grid grid-cols-1 gap-4 pb-40 lg:grid-cols-3&quot;]/a[2]/div[@class=&quot;px-3 rounded-lg  flex auto p-4 flex-col&quot;]/img[@class=&quot;object-cover rounded-lg&quot;]</value>
      <webElementGuid>51576b02-8e71-4fe2-9bb0-51767c44fa38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/div/a[2]/div/img</value>
      <webElementGuid>862ef968-f3ef-4aad-a114-40e24b8b24e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Picture of the author'])[2]</value>
      <webElementGuid>222b227e-1131-4f0e-a536-82a90267abb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/img</value>
      <webElementGuid>b65d4933-49cc-4640-b016-64c5a1b5a81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Picture of the author' and @src = '/_next/static/media/choicefaculty2.ed9d815d.svg']</value>
      <webElementGuid>b8208cb5-73e9-4ebc-8a63-fc91e5fb42f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
