<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kaleidoskop 2018 29 Kepala Daerah Terjera_22bc1c</name>
   <tag></tag>
   <elementGuidId>815b0c53-8f77-4763-b826-f4278f020fd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93423143-d44f-4111-a4fa-ceb280a805fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>42a98f5e-ddd2-4621-976c-259b4e6e6713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2018/12/18/12495661/kaleidoskop-2018-29-kepala-daerah-terjerat-kasus-korupsi&amp;sa=U&amp;ved=2ahUKEwiR4_6i7Jz_AhWJAYgKHQ0RCGcQFnoECAkQAg&amp;usg=AOvVaw3gWsp7GHiN1St2OamGowb9</value>
      <webElementGuid>57ca7f10-a181-4906-921f-4d59c0ddffbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>b00271f6-5ca9-4219-9024-2dcacaaabdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>fd977a9a-0dcc-4e5d-a473-ee702e0242a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2018/12/18/12495661/kaleidoskop-2018-29-kepala-daerah-terjerat-kasus-korupsi&amp;sa=U&amp;ved=2ahUKEwiR4_6i7Jz_AhWJAYgKHQ0RCGcQFnoECAkQAg&amp;usg=AOvVaw3gWsp7GHiN1St2OamGowb9</value>
      <webElementGuid>e2b9a9e0-5433-4fc3-8d01-e9382d5ef092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://nasional.kompas.com/read/2018/12/18/12495661/kaleidoskop-2018-29-kepala-daerah-terjerat-kasus-korupsi</value>
      <webElementGuid>1bfd1f5f-efae-4894-b567-9b1cf8dda53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaleidoskop 2018: 29 Kepala Daerah Terjerat Kasus Korupsi</value>
      <webElementGuid>f7da9700-29f2-4329-a80c-ecd002462000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]/div[@class=&quot;gs-webResult gs-result&quot;]/div[@class=&quot;gsc-thumbnail-inside&quot;]/div[@class=&quot;gs-title&quot;]/a[@class=&quot;gs-title&quot;]</value>
      <webElementGuid>2a7c2d41-7ffc-40df-a2ab-fce248e116fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>4662f34b-37c2-40b6-9099-14ce0262cece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clipped from Google - 5/2023'])[1]/following::a[1]</value>
      <webElementGuid>bb8eaadb-0986-4ae9-bffb-f1fdac5d3ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='korupsi'])[3]/following::a[2]</value>
      <webElementGuid>9c3d01f8-0c7b-4837-b0c9-7282814b9574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nasional.kompas.com'])[3]/preceding::a[1]</value>
      <webElementGuid>75946851-b5e6-4222-9656-3ff2c2a61404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kaleidoskop 2018: 29 Kepala Daerah Terjerat Kasus']/parent::*</value>
      <webElementGuid>82f79df3-a616-4e64-a497-7c54c328df13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2018/12/18/12495661/kaleidoskop-2018-29-kepala-daerah-terjerat-kasus-korupsi&amp;sa=U&amp;ved=2ahUKEwiR4_6i7Jz_AhWJAYgKHQ0RCGcQFnoECAkQAg&amp;usg=AOvVaw3gWsp7GHiN1St2OamGowb9')]</value>
      <webElementGuid>bd2aa97a-b651-4460-85d9-be1e9926dff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>20a76048-bbe9-4863-94fb-26231b70128b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2018/12/18/12495661/kaleidoskop-2018-29-kepala-daerah-terjerat-kasus-korupsi&amp;sa=U&amp;ved=2ahUKEwiR4_6i7Jz_AhWJAYgKHQ0RCGcQFnoECAkQAg&amp;usg=AOvVaw3gWsp7GHiN1St2OamGowb9' and (text() = 'Kaleidoskop 2018: 29 Kepala Daerah Terjerat Kasus Korupsi' or . = 'Kaleidoskop 2018: 29 Kepala Daerah Terjerat Kasus Korupsi')]</value>
      <webElementGuid>81cc4617-c109-4e93-8c4d-5975ffe5042c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
