<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Belum</name>
   <tag></tag>
   <elementGuidId>c12853c6-041a-4353-98da-77cc6f31423b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f32de534-24bd-4592-8142-7389f40fcfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[230px] h-[56px] bg-[#106FA4] rounded-[8px] text-white</value>
      <webElementGuid>6879bf81-4e32-430a-b99f-1aa272b05db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c9443cc-8909-479a-8b60-7cd32d7a1d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum</value>
      <webElementGuid>042c8f67-0e98-430b-91da-2905c6a8a4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;min-h-screen bg-[#FAFAFA] px-[70px] w-full&quot;]/div[2]/div[2]/div[@class=&quot;p-8 overflow-auto whitespace-nowrap&quot;]/div[@class=&quot;relative z-50&quot;]/div[@class=&quot;fixed inset-0 z-10 overflow-y-auto&quot;]/div[@class=&quot;flex items-center justify-center w-full min-h-full p-4 text-center sm:items-center sm:p-0&quot;]/div[@class=&quot;relative w-auto overflow-hidden text-left transition-all transform rounded-lg shadow-xl sm:my-8 undefined&quot;]/div[@class=&quot;w-full px-4 pt-5 pb-4 bg-white sm:p-6 sm:pb-4&quot;]/div[@class=&quot;mt-3 text-center sm:mt-0 sm:text-left&quot;]/div[@class=&quot;flex items-center w-full&quot;]/div[@class=&quot;flex flex-col items-center justify-center w-full py-10 text-center dark:bg-[#222529] !h-80 !w-[100%] text-md py-10&quot;]/div[@class=&quot;flex w-full flex-col justify-center&quot;]/div[@class=&quot;flex gap-3 my-2 py-4&quot;]/button[@class=&quot;w-[230px] h-[56px] bg-[#106FA4] rounded-[8px] text-white&quot;]</value>
      <webElementGuid>c4b48b5c-9f3c-45ba-abad-761b7cc159d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>8d06113e-18ca-4178-9c41-ad8c47430a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section/div[2]/div[2]/div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>4eff659a-d627-45ba-85c7-6799324fada8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pernah'])[1]/following::button[1]</value>
      <webElementGuid>44c4448c-9613-47c7-9ad4-2194f0fb3861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda sudah mempelajari mata kuliah ini?'])[1]/following::button[2]</value>
      <webElementGuid>22239e55-81ea-410f-b0bc-ed59ef7fa4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Belum']/parent::*</value>
      <webElementGuid>6a5c4fcf-508d-4237-91da-4e32104717ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c315f82b-8bcd-479f-bc27-ef35c8fd4603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Belum' or . = 'Belum')]</value>
      <webElementGuid>48d807e1-c367-4a47-b729-ef23fe0bb180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
