<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tambah</name>
   <tag></tag>
   <elementGuidId>1a02e157-ca8d-4299-ac53-f388b83a3af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/section/div[2]/div[2]/div[2]/div/div[2]/div[6]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.flex.gap-2.items-center.p-4.font-semibold.text-blue-600</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4bab602-b3be-48e6-b2af-82ccfde95c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex gap-2 items-center p-4 font-semibold text-blue-600</value>
      <webElementGuid>6366e6ac-6ca8-4b1a-8f01-76ba312c58e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> tambah </value>
      <webElementGuid>7fe1c86a-a2e2-4dc9-b73a-ca56ec4ac34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;min-h-screen bg-[#FAFAFA] px-[70px] w-full&quot;]/div[2]/div[2]/div[@class=&quot;p-8 overflow-auto whitespace-nowrap&quot;]/div[@class=&quot;grid grid-flow-row auto-rows-auto&quot;]/div[@class=&quot;grid grid-flow-col auto-cols-min mx-auto border border-[#e5e7eb] divide-neutral-400 dark:divide-gray-700 w-full text-[16px]&quot;]/div[@class=&quot;w-[177px] dark:divide-gray-700 lg:text-start text-center py-3 font-medium md:text-[16px] lg:text-[16px] text-[10px] dark:bg-transparent&quot;]/button[@class=&quot;flex gap-2 items-center p-4 font-semibold text-blue-600&quot;]</value>
      <webElementGuid>e516cd3c-6ac4-499e-8556-70bcd5430454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section/div[2]/div[2]/div[2]/div/div[2]/div[6]/button</value>
      <webElementGuid>77d8f034-ede4-4b34-8581-35cca1ffdfe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Inggris'])[1]/following::button[1]</value>
      <webElementGuid>258c7bd2-c77b-43fa-906e-6a6c0297cf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tindakan'])[1]/following::button[1]</value>
      <webElementGuid>61a4fbf6-d108-469c-8371-a2a273a7a525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalkulus'])[1]/preceding::button[1]</value>
      <webElementGuid>51dc4285-7d2d-4db9-8f67-5be9ce4e8e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tambah'])[2]/preceding::button[1]</value>
      <webElementGuid>0e541ebd-7d5d-4c3a-ae86-2aff46fb6269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tambah']/parent::*</value>
      <webElementGuid>97625b6d-7994-43f0-84b2-6173c1c2fe05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>4e357653-1eeb-450d-affe-970f4f878624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' tambah ' or . = ' tambah ')]</value>
      <webElementGuid>8cfec293-688b-458d-a93e-f84b0782bfa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
