<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terlambat</name>
   <tag></tag>
   <elementGuidId>901a5451-4fbe-4912-93e6-84c2fbc7b57b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/section[2]/div/div/ul/li[3]/button/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba7de4bd-cae1-4a56-9e74-9b005a63702f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block p-4      rounded-t-lg active hover:border-gray-300 dark:hover:text-gray-300 dark:text-[#0B568D]  </value>
      <webElementGuid>413e1776-2450-4a53-b767-82458f63daaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>7e5aa035-885a-4619-a4c4-94dd49b3b980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terlambat</value>
      <webElementGuid>c23e281a-cb96-4d5d-ad16-d01ee2dc0b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;lg:px-20 md:px-10 px-5 py-3 w-full mt-[36px] drop-shadow-md mb-3 min-h-screen&quot;]/div[@class=&quot;bg-white h-full rounded-[8px] dark:bg-gray-800&quot;]/div[@class=&quot;text-[20px] font-semibold text-center text-[#262626] border-b border-gray-200 hover:text-[#000] px-[50px] mb-10&quot;]/ul[@class=&quot;flex flex-wrap&quot;]/li[@class=&quot;mr-2&quot;]/button[1]/a[@class=&quot;inline-block p-4      rounded-t-lg active hover:border-gray-300 dark:hover:text-gray-300 dark:text-[#0B568D]&quot;]</value>
      <webElementGuid>e20b7b88-e233-488e-a829-1380654457e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section[2]/div/div/ul/li[3]/button/a</value>
      <webElementGuid>2303a838-3bca-4a28-99ad-7cc35da1b875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terlambat')]</value>
      <webElementGuid>5d7beb43-d8ec-4822-b987-a055351edfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ditugaskan'])[1]/following::a[1]</value>
      <webElementGuid>4e9a4d61-83ec-4bd2-922b-c3ba1b2929b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Tugas'])[1]/following::a[2]</value>
      <webElementGuid>a41b9f15-8150-4510-a20f-f18f0f23e4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Dinilai'])[1]/preceding::a[1]</value>
      <webElementGuid>f0c7ba67-008d-49bd-b59f-8f71eab05011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[1]/preceding::a[2]</value>
      <webElementGuid>91272556-204b-429e-86f9-25f9be9cb8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terlambat']/parent::*</value>
      <webElementGuid>aa4d1d5d-04d6-4978-81b5-2888e72d60d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button/a</value>
      <webElementGuid>85c4054f-22e3-4100-a848-adf9c0a3ee4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Terlambat' or . = 'Terlambat')]</value>
      <webElementGuid>09de4c96-bde1-4b47-b8e6-15e9eb8725ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
