<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dashboard_bg-neutral-100 w-9 h-9 flex i_06f240</name>
   <tag></tag>
   <elementGuidId>95b898ad-3aa6-4031-b60f-c13e9a292910</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='feature-menu']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bg-neutral-100.w-9.h-9.flex.items-center.justify-center.rounded-md.shadow-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62fe17b8-7a53-46b1-95af-bf4bfe6337bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-neutral-100 w-9 h-9 flex items-center justify-center rounded-md shadow-sm</value>
      <webElementGuid>5a445d86-cf90-4101-8271-4b879e840c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feature-menu&quot;)/div[@class=&quot;bg-neutral-100 w-9 h-9 flex items-center justify-center rounded-md shadow-sm&quot;]</value>
      <webElementGuid>b21709ce-c121-46b9-b9c3-9da97c0f8b6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='feature-menu']/div</value>
      <webElementGuid>f74fc69c-2d13-40a9-a1b5-4e620ee6770d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[4]</value>
      <webElementGuid>f4a3cd79-ecfd-4e32-9de7-b8a9ca371f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::div[2]</value>
      <webElementGuid>a7478e12-c27c-47e4-9b8f-44f6ebb2608a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/preceding::div[8]</value>
      <webElementGuid>b9572d96-4cb6-4a23-86f3-7bab1783427c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>41290eda-a267-4c92-8260-a3c0da1ad9e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
