<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Admin                Mahasiswa      _f5f375</name>
   <tag></tag>
   <elementGuidId>3d521a91-64e4-4462-aba2-00511cd70848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='roles']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#roles</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8cd4b0cf-4f63-432f-bb1e-2e60d72beded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roles</value>
      <webElementGuid>44a6f30a-bfb1-4492-ab4b-4dcfb7fd85aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>roles</value>
      <webElementGuid>1a0fcb66-97cf-4854-a554-1e0fd9fc8714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-form</value>
      <webElementGuid>478d9e02-fad5-409f-a60d-21e964cc1bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Admin
                Mahasiswa
                Duktek
            </value>
      <webElementGuid>6debde78-8bb0-4ef5-ac39-faa30a95ce6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tambahData&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;modal-body&quot;]/select[@id=&quot;roles&quot;]</value>
      <webElementGuid>fa154748-65fb-4fd4-8162-c38546d9ba62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='roles']</value>
      <webElementGuid>ac42e7b0-de17-48e0-bd35-1c07249a880f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tambahData']/div/div/form/div/select</value>
      <webElementGuid>4fdedb20-3111-46be-9acb-bcfa061c402d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah User'])[1]/following::select[1]</value>
      <webElementGuid>cd0cac25-069b-4685-aab7-9a1f92251345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mahasiswa'])[7]/following::select[1]</value>
      <webElementGuid>46b957f1-8b60-47da-b072-5624dba8e2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::select[1]</value>
      <webElementGuid>e917cd88-a0d5-4dfd-a0e3-b4db53bfb709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save changes'])[1]/preceding::select[1]</value>
      <webElementGuid>af8bb071-2485-42c2-8c0f-d2b9fd75f226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>acade276-606b-4ac0-af35-3e96c6de44e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'roles' and @id = 'roles' and (text() = '
                Admin
                Mahasiswa
                Duktek
            ' or . = '
                Admin
                Mahasiswa
                Duktek
            ')]</value>
      <webElementGuid>ee317a72-65e3-4704-8d5b-8abf3b00ed3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
