<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AdministrasiFitur administrasi pada web_52b92b</name>
   <tag></tag>
   <elementGuidId>f561b3d3-af4f-4e2a-adbc-2b5d2ad70d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/section/section/div[4]/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.items-start.justify-start.flex.flex.auto.p-2.flex-col</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9f38ffb-82d8-45da-97ab-9baacb38190e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items-start justify-start flex  flex auto p-2 flex-col</value>
      <webElementGuid>c7da5805-3ba2-4bd6-8f13-568c43129da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AdministrasiFitur administrasi pada website KG berisi informasi dan fitur yang memungkinkan Kamu untuk bisa mengelola dan mengakses semua fitur pada website.</value>
      <webElementGuid>c657cacd-d285-4d15-98e4-7ba2d5f3a369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/div[1]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;py-[40px] lg:px-[72px] md:px-[72px] px-[20px] bg-neutral-100 dark:bg-[#222529] w-full&quot;]/div[@class=&quot;grid grid-cols-12  lg:gap-x-[40px] md:gap-x-[40px] gap-x-[20px] gap-y-[34px]&quot;]/div[@class=&quot;lg:col-span-3 md:col-span-4 col-span-6 lg:py-[8px] md:py-[25px] py-[15px] rounded-lg bg-white z-10 shadow-2xl&quot;]/a[1]/div[@class=&quot;items-start justify-start flex  flex auto p-2 flex-col&quot;]</value>
      <webElementGuid>2af444ff-41e8-4ebb-aa97-01ca0c8730ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/section/div[4]/div/a/div</value>
      <webElementGuid>590a397e-77a2-4b7b-ab8e-7a69431f6ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur Kampus Gratis'])[1]/following::div[4]</value>
      <webElementGuid>a4217885-d8f5-4f53-8c43-cde768090031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Fitur'])[2]/following::div[7]</value>
      <webElementGuid>bec9eaff-438f-4d9d-88d1-43ac6c2a1864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rencana Studi'])[1]/preceding::div[2]</value>
      <webElementGuid>3cde5762-ad41-43c3-8674-8369bad95c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>92117fe7-9225-41d3-8a19-e12a2b60586d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AdministrasiFitur administrasi pada website KG berisi informasi dan fitur yang memungkinkan Kamu untuk bisa mengelola dan mengakses semua fitur pada website.' or . = 'AdministrasiFitur administrasi pada website KG berisi informasi dan fitur yang memungkinkan Kamu untuk bisa mengelola dan mengakses semua fitur pada website.')]</value>
      <webElementGuid>0c8fa545-c450-46b4-b908-8bccd0c74983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
