<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Selesai</name>
   <tag></tag>
   <elementGuidId>f6137c6a-8ec2-41f3-bea8-7df8554c8211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/section[2]/div/div/ul/li[5]/button/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24eee755-67be-48a1-9fc6-01d51cb84922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block p-4      rounded-t-lg active hover:border-gray-300 dark:hover:text-gray-300 dark:text-[#0B568D]</value>
      <webElementGuid>0da39f5c-e922-4728-8925-96408d817a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>d9ae1dbb-5854-4800-8bb7-1a116c5bfbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>df52d346-f00a-4470-be92-a665ee237af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;lg:px-20 md:px-10 px-5 py-3 w-full mt-[36px] drop-shadow-md mb-3 min-h-screen&quot;]/div[@class=&quot;bg-white h-full rounded-[8px] dark:bg-gray-800&quot;]/div[@class=&quot;text-[20px] font-semibold text-center text-[#262626] border-b border-gray-200 hover:text-[#000] px-[50px] mb-10&quot;]/ul[@class=&quot;flex flex-wrap&quot;]/li[@class=&quot;mr-2&quot;]/button[1]/a[@class=&quot;inline-block p-4      rounded-t-lg active hover:border-gray-300 dark:hover:text-gray-300 dark:text-[#0B568D]&quot;]</value>
      <webElementGuid>af2204d5-2dfc-4247-bedf-5cafd3b1aa4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section[2]/div/div/ul/li[5]/button/a</value>
      <webElementGuid>9f9e04f9-585c-4f35-85c4-7cdb522998a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Selesai')]</value>
      <webElementGuid>c1ca68c9-d94e-4b5e-9a2c-550e22470c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Dinilai'])[1]/following::a[1]</value>
      <webElementGuid>4b523ba6-d552-4a09-8ad9-58e4853b06e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terlambat'])[1]/following::a[2]</value>
      <webElementGuid>771f03a0-fc64-4e3b-8985-6f5f0899e304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>06838168-bfc4-4b24-a1e3-92321cb12005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/button/a</value>
      <webElementGuid>6976b0d2-87a7-415c-93d9-e6d262c2d395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>abc80ece-f3f0-4bca-8ce0-41ce24693a3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
