<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password</name>
   <tag></tag>
   <elementGuidId>f5dff145-624c-4861-b01d-46d8a5713a0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e60de47-6a36-4cc0-aa1c-f6c24d9e5c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0eb71db0-708c-4a2f-b21b-45c9282877eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>control</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>06248644-6ca5-4fdc-8dc9-111a1b424afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e75e051-d178-43c7-a964-b711ab16223f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>************</value>
      <webElementGuid>5771c06e-5213-4926-b840-b0ebd15e3841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>480a2cd1-a45f-4b01-b103-308e32c43b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none focus:outline-none w-full text-[#000] text-sm border-[0.5px] border-neutral-400 shadow-sm py-4 rounded-lg  px-4 </value>
      <webElementGuid>c45ec941-737c-45d3-be0e-afe5be71a53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;w-full bg-neutral-100 flex justify-center items-center lg:py-10 lg:px-14 md:p-8 sm:p-6 p-4 h-screen&quot;]/section[@class=&quot;flex items-center bg-white w-full h-full rounded-lg shadow-lg&quot;]/div[@class=&quot;flex-col md:gap-y-[57px] gap-y-6 items-center justify-center p-6 flex h-full w-full lg:w-1/2&quot;]/div[@class=&quot;flex flex-col w-full items-start pb-[37px] justify-start&quot;]/form[@class=&quot;flex flex-col w-full justify-start&quot;]/section[@class=&quot;flex flex-col w-auto my-1 gap-y-2&quot;]/section[@class=&quot;relative flex items-center w-auto&quot;]/input[@class=&quot;outline-none focus:outline-none w-full text-[#000] text-sm border-[0.5px] border-neutral-400 shadow-sm py-4 rounded-lg  px-4&quot;]</value>
      <webElementGuid>7f860683-b885-4f8d-b225-1cfce11af4b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>dd25abb7-a3d2-40a4-9672-5ac16ee84551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section/div[2]/div[2]/form/section[2]/section/input</value>
      <webElementGuid>990bd487-626a-414a-9d7c-b3c497ff81d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section/input</value>
      <webElementGuid>3c884153-7a16-4bbb-b96c-78a42951abea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = '************']</value>
      <webElementGuid>e7cd5663-dbda-4a26-bc88-c4f9de0bafea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
