<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sedang Dinilai</name>
   <tag></tag>
   <elementGuidId>cbce5ccc-9e23-467c-9718-2803f2517f4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/section[2]/div/div/ul/li[4]/button/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d79367c-9e52-4da8-89f3-a9b9ed9e976e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block p-4      rounded-t-lg active hover:border-gray-300 dark:hover:text-gray-300 dark:text-[#0B568D] </value>
      <webElementGuid>523c8bb2-6c4a-46fb-83b8-dafb1252e3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>2c2182c4-5d13-4461-8496-8c55ab39f8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sedang Dinilai</value>
      <webElementGuid>cab0da56-a393-4162-b01e-e682247751d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/section[@class=&quot;lg:px-20 md:px-10 px-5 py-3 w-full mt-[36px] drop-shadow-md mb-3 min-h-screen&quot;]/div[@class=&quot;bg-white h-full rounded-[8px] dark:bg-gray-800&quot;]/div[@class=&quot;text-[20px] font-semibold text-center text-[#262626] border-b border-gray-200 hover:text-[#000] px-[50px] mb-10&quot;]/ul[@class=&quot;flex flex-wrap&quot;]/li[@class=&quot;mr-2&quot;]/button[1]/a[@class=&quot;inline-block p-4      rounded-t-lg active hover:border-gray-300 dark:hover:text-gray-300 dark:text-[#0B568D]&quot;]</value>
      <webElementGuid>2b626b23-4c6e-489c-a7c4-e17e3613deec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section[2]/div/div/ul/li[4]/button/a</value>
      <webElementGuid>bef9ab51-20a3-4c03-aa36-2d5a419335f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sedang Dinilai')]</value>
      <webElementGuid>dfbb85b4-fbd2-49fe-97d5-394887935760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terlambat'])[1]/following::a[1]</value>
      <webElementGuid>5a065aec-7170-46be-b834-192d8007550e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ditugaskan'])[1]/following::a[2]</value>
      <webElementGuid>147e6905-c47f-4e15-a21a-346be4cb4510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[1]/preceding::a[1]</value>
      <webElementGuid>454eca5a-211d-4cb3-9d11-6ab9a733546f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment UTS'])[1]/preceding::a[2]</value>
      <webElementGuid>c00d9340-6e16-4cf1-873c-dd9d2a1a9ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sedang Dinilai']/parent::*</value>
      <webElementGuid>10483053-96e6-4cff-8184-6ec3298f0e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button/a</value>
      <webElementGuid>a00cc0fe-c9f1-4dad-bac3-c0490c192dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Sedang Dinilai' or . = 'Sedang Dinilai')]</value>
      <webElementGuid>7cc76137-43d0-4a23-8e21-400c1fe980eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
