<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pembiayaan dan Optimalisasi Bisnis</name>
   <tag></tag>
   <elementGuidId>171c28d6-c0f8-4488-82ca-fec00f7bd0e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div/div[2]/div[2]/a/div/section/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>334ca936-a601-479e-a21e-ed77442717bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xl mt-0 text-[#106FA4] w-full</value>
      <webElementGuid>1ed386ce-3a83-4f26-8068-f42e3ea8e4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pembiayaan dan Optimalisasi Bisnis</value>
      <webElementGuid>fb83ff60-e454-45bb-90c0-fd5a18388e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;bg-white&quot;]/div[@class=&quot;px-10&quot;]/div[@class=&quot;grid grid-cols-1 gap-4 pb-40 lg:grid-cols-4&quot;]/a[1]/div[@class=&quot;px-3 rounded-lg  flex auto p-4 flex-col&quot;]/section[@class=&quot;flex&quot;]/div[@class=&quot;text-xl mt-0 text-[#106FA4] w-full&quot;]</value>
      <webElementGuid>78a965c3-c294-45e5-9be1-2df8e550e836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/div[2]/div[2]/a/div/section/div</value>
      <webElementGuid>d5524aae-02c6-4759-96a4-1c06c493c53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamu hanya bisa mengambil satu(1) program studi'])[1]/following::div[6]</value>
      <webElementGuid>c7821eee-75e4-4c11-915e-7a14f1d71a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[12]</value>
      <webElementGuid>92159e9f-b162-4828-86e6-2d348a7d1c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pembiayaan dan Optimalisasi Bisnis']/parent::*</value>
      <webElementGuid>9f3c89fc-0782-45d3-9960-560577be37ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/section/div</value>
      <webElementGuid>c1c08681-59cc-4325-a8a2-ac8a6d5ceb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pembiayaan dan Optimalisasi Bisnis' or . = 'Pembiayaan dan Optimalisasi Bisnis')]</value>
      <webElementGuid>1f01d4d7-d7c8-4eaf-a23f-793ae3c94681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
