<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email</name>
   <tag></tag>
   <elementGuidId>60d0c6d1-3c60-4d51-b707-6b71f69932ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a72f9c18-776b-4136-b736-188099e23a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>262fbb5c-9d1a-4c7c-bdeb-db6fa2b7381d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>control</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>0ef5d117-e544-4586-b231-e4995a127702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b5cc44fc-a9de-42d1-8a2c-e327b688a77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Anda</value>
      <webElementGuid>4813c8c2-53d0-4426-8f24-e2e4e6146c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>acfaad2c-beb4-472a-a188-8ad0ce1c6f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none focus:outline-none w-full text-[#000] text-sm focus:ring-1 focus:ring-error-base bg-error-100 placeholder:text-white ring-1 ring-error-base text-sm py-4 rounded-lg  px-4 </value>
      <webElementGuid>553573b5-4033-4b43-b76c-c64e39e90b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>aafe60a6-5e38-48fe-8fe0-617db26011b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>message</name>
      <type>Main</type>
      <value>Email harus valid</value>
      <webElementGuid>868a726f-2c2f-4907-9e2c-253edfa279c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;font-montserrat&quot;]/section[@class=&quot;w-full bg-neutral-100 flex justify-center items-center lg:py-10 lg:px-14 md:p-8 sm:p-6 p-4 h-screen&quot;]/section[@class=&quot;flex items-center bg-white w-full h-full rounded-lg shadow-lg&quot;]/div[@class=&quot;flex-col md:gap-y-[57px] gap-y-6 items-center justify-center p-6 flex h-full w-full lg:w-1/2&quot;]/div[@class=&quot;flex flex-col w-full items-start pb-[37px] justify-start&quot;]/form[@class=&quot;flex flex-col w-full justify-start&quot;]/section[@class=&quot;flex flex-col w-auto my-1 gap-y-2&quot;]/section[@class=&quot;relative flex items-center w-auto&quot;]/input[@class=&quot;outline-none focus:outline-none w-full text-[#000] text-sm focus:ring-1 focus:ring-error-base bg-error-100 placeholder:text-white ring-1 ring-error-base text-sm py-4 rounded-lg  px-4&quot;]</value>
      <webElementGuid>9ac9f45e-5dd7-4755-a9d9-853697f166b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>c90a7534-0d26-40ba-bd6c-65c8c8d629a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/section/div[2]/div[2]/form/section/section/input</value>
      <webElementGuid>0c69bdff-3264-4019-992f-7b6091790e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1681d8fd-2670-4488-9378-b8f087b1472f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @placeholder = 'Masukkan Email Anda']</value>
      <webElementGuid>f96ec143-768f-4615-b7fc-8696483a73ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
